# Generated by Django 4.1 on 2024-04-22 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "user_key",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="worker_info",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("order_success_count", models.IntegerField(default=0)),
                ("attitude_score", models.FloatField(default=0)),
                ("quality_score", models.FloatField(default=0)),
                ("overall_score", models.FloatField(default=0)),
            ],
        ),
    ]
